server:
  context-path: /
  port: 8080
# ES
spring:
  data:
    elasticsearch:
      cluster-name: elasticsearch #默认即为 elasticsearch
      cluster-nodes: 10.10.13.14:9300 #配置es节点信息，逗号分隔，如果没有指定，则启动ClientNode